TODO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
    # path('user/', include('user_app.urls')),


]

todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'
urlpatterns = [
    path('', views.login_user, name='login_user'),
    path('logout', views.logout_user, name='logout_user'),
    path('signup', views.signup_user, name='signup_user'),
    path('profile/', views.profile, name='profile'),
    path('add', views.add, name='add'),
    path('about', views.about, name='about'),
    path('edit/<int:todo_id>', views.edit, name='edit'),
    path('delete/<int:todo_id>', views.delete, name='delete'),
    # path('confirm_delete/<int:todo_id>', views.confirm_delete, name='confirm_delete'),


]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    todo_title = models.CharField(max_length=250, default='Add your TODO here', blank=False)
    todo_description = models.TextField(blank=True, default='Your todo description ')
    is_todo_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='media/profile_pic/%Y/%m/', blank=True, default='default.jpg')

    def __str__(self):
        return self.user.username

todo_app/forms.py
from django import forms
from .models import Todo, Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# for add delete edit
class TaskForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'
        exclude = ['user']


# for signup
class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ['first_name',
                  'last_name',
                  'username',
                  'email',
                  'password1',
                  'password2'
                  ]


# for login
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['profile_image',]


class UserUpdateForm(forms.ModelForm):

    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

todo_app/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Todo
from .forms import UserRegisterForm, LoginForm, TaskForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required


# for login
def login_user(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print(request.POST)
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Successfully Logged In")
                redirect_url = request.GET.get('next', 'todo_app:add')
                return redirect(redirect_url)
            else:
                messages.error(request, "Invalid credentials! Please try again")
                return redirect("todo_app:login_user")
    # if a GET (or any other method) we'll create a blank form
    else:
        form = LoginForm()
    return render(request, 'todo_app/login.html', {'form': form})


# for signing up user
def signup_user(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = User.objects.create_user(
                username=username, password=password, email=email)
            user.save()
            messages.success(request, "Your profie has been successfully created")
            return redirect('todo_app:login_user')
    else:
        form = UserRegisterForm()
    data_for_frontend = {
        'form': form
    }
    return render(request, 'todo_app/signup.html', data_for_frontend)


# for logging out user
def logout_user(request):
    logout(request)
    return redirect('todo_app:login_user')


# for add items in todo list
@login_required(login_url='todo_app:login_user')
def add(request):
    todo_list = Todo.objects.filter(user=request.user).order_by('is_todo_completed')
    if request.method == "POST":
        todo_title = request.POST['todo_title']
        todo_list = Todo(
            user=request.user,
            todo_title=todo_title
        )
        todo_list.save()
        return redirect('todo_app:add')
    data_for_frontend = {
        'todo_list': todo_list,
    }
    return render(request, 'todo_app/add.html', data_for_frontend)


# for editing item in todo list
@login_required(login_url='todo_app:login_user')
def edit(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    form = TaskForm(request.POST or None, instance=todo)
    if form.is_valid():
        form.save()
        # form = TaskForm()
        return redirect('todo_app:add')
    data_for_frontend = {
        'form': form,
    }
    print(request.POST)
    return render(request, 'todo_app/edit.html', data_for_frontend)


# for deleting item in todo list
def delete(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    # if request.method == "POST":
    #     todo.delete()
    #     return redirect("todo_app:add")
    # data_for_frontend = {
    #     'todo': todo,
    # }
    # return render(request, 'todo_app/delete.html', data_for_frontend)
    todo.delete()
    return redirect('todo_app:add')


# def confirm_delete(request, todo_id):
#     todo = Todo.objects.get(id=todo_id)
#     todo.delete()
#     return render(request, 'todo_app/add.html')


def about(request):
    return render(request, 'todo_app/about.html')


@login_required(login_url='todo_app:login_user')
def profile(request):
    print(request.user.profile.whatever)
    HttpResponse({'ll'})

todo_app/templates/todo_app/about.html
{% extends 'todo_app/add.html' %}
{% load crispy_forms_tags %}
{% block parent %}
<h2>What is a ToDo List?
    Simple tool to organise everything
    What is a ToDo List? Simple tool to organise everything </h2>
<p>
What is a todo list and how can it help in business and daily life?

Do any of the following seem familiar?

    You often feel completely overwhelmed with the amount of work you’ve got to do?
    You sometimes forget to do things that are important
    People have to chase you to get things done
    You find it a struggle to keep to deadlines

Don’t think you’re unusual because there are thousands of people who struggle with the same every day, not just in the workplace but in their personal life too. Luckily, there is something very simple you can do to keep your life and work more organised.
What is a ToDo List?
</p>

<h3>What is a ToDo List?</h3>
<p>The definition is a simple one. It’s a list of tasks you need to complete, or things that you want to do.

Most typically, they’re organised in order of priority. Traditionally, they’re written on a piece of paper or post it notes and acts as a memory aid. As technology has evolved we have been able to create a todo lists with excel spreadsheets, word documents, email lists, todo list apps, microsoft to do and google to do list to name a few. You can use a to do list in your home and personal life, or in the workplace.

    Having a list of everything you need to do written down in one place means you shouldn’t forget anything important. By prioritising the tasks in the list you plan the order in which you’re going to do them and can quickly see what needs your immediate attention and what tasks you can leave until a little later.</p>
<h3>The Benefits of Using a To Do List</h3>

<p>One of the most important reasons you should use a to do list is that it will help you stay organised. When you write all your tasks in a list, they seem more manageable. When you’ve got a clear outline of the tasks you’ve got to do and those you’ve completed, it helps you stay focused. While freeing up space in your mind for other more creative tasks.

When you complete a task, you can cross it off your list. This gives you a sense of progress and achievement, something you’ll lack if you’re always rushing from one task to the next. If you feel a sense of achievement, it spurs you on and motivates you to keep moving forward.

But that’s not the only benefits of a to do list. Here are a few more:
<ul>
    <li>    <strong>Improves your memory:</strong> A to do list acts as an external memory aid. It’s only possible to hold a few pieces of information at one time. Keep a to do list and you’ll be able to keep track of everything, rather than just a few of the tasks you need to do. Your to do list will also reinforce the information, which makes it less likely you’re going to forget something.
</li>
    <li><strong>Increases productivity:</strong> A to do list allows you to prioritize the tasks that are more important. This means you don’t waste time on tasks that don’t require your immediate attention. Your list will help you stay focused on the tasks that are the most important.
</li>
    <li><strong>Helps with motivation:</strong>To do lists are a great motivational tool because you can use them to clarify your goals. You can divide your long-term goal into smaller, more achievable short-term goals and as you tick each one off your list, your confidence will increase.</p>
</li>
</ul>


<h3>What is a ToDo List in business and why is it important?</h3>

<p>It seem such a simple solution by putting pen to paper and taking time out of your day to create a to do list, a plan for your day helps define your challenges and goals. Preventing time being wasted trying to identify what is the next most important task to tackle next and even more important makes sure you don’t forget to do something important.

    To-do lists offer a way to increase productivity, stopping you forgetting things, helps prioritise task, manage tasks effectively, use time wisely and improve time management as well as workflow.</p>
<h3>What Makes a Great To Do List App?</h3>

<p>To do lists come in all shapes and sizes. It always used to be something that you would write using pen and paper, but thanks to technology there’s an app that can come to the rescue. What makes a good to do list app?
<ul>
    <li>Tasks should be fast to add and organise</li>
    <li> There should be a variety of ways to organise the tasks</li>
    <li> Ability to plan your workflow</li>
    <li>Setting priorities</li>
    <li>Reminders for any self-imposed deadlines.</li>
    <li> Allocation of tasks if using it for task management with a team. Team to-do list allows you to assign to the best person for the job.</li>
    <li>Able to synch between different platforms</li>
</ul>


    All it takes is just a few minutes every day to keep a to do list up to date. With a to do list, you can complete goals without wasting time trying to figure out priorities. Your productivity will increase, you won’t forget things, your time management will improve and you’ll be able to manage your tasks more effectively.</p>
{% endblock parent %}

todo_app/templates/todo_app/add.html
{%extends 'todo_app/base.html'%}
{% include 'todo_app/confirm_delete.html' %}
{% block navbar%}
{%if user.is_authenticated%}
<li class="nav-item dropdown ml-2">
    <a class="nav-link dropdown-toggle" href='#' id="navbarDropdown" role="button" data-toggle="dropdown">
        {{request.user}}</a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
<!--        <li><a class="dropdown-item" href="/profile">Your profile</a></li>-->
<!--        <li><a class="dropdown-item" href="/profile">update profile</a></li>-->
        <li><a class="dropdown-item" href="/logout">Sign out</a></li>


    </ul>

</li>


{%else%}
<div class="d-grid gap-2 d-md-block mx-2">
    <a href="{% url 'todo_app:login_user' %}">
        <button class="btn btn-success" type="button">Log in</button>
    </a>
    <a href="{% url 'todo_app:signup_user' %}">
        <button class="btn btn-success" type="button">Sign up</button>
    </a>
</div>

{%endif%}

{%endblock navbar%}
{%block parent%}
{%if user.is_authenticated%}
<div class="mt-4">
    <h2 class="fw-bold fs-1">ADD ITEM IN YOUR TODO LIST</h2>

    <form class="mt-5" action="{% url 'todo_app:add' %}" method="post">{%csrf_token%}
        <div class="form-row align-items-center">
            <div class="col-auto">

                <input type="text" class="form-control mb-2" name="todo_title" placeholder="add todo item..">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-2" name="action">ADD</button>
            </div>
        </div>
    </form>

</div>

<div class="mt-4">
    <ul class="list-group">
        {%for todo in todo_list%}
        <li class="list-group-item mt-4">{{todo}}
            <div class="float-right">
                <!--            <form action="delete_todo/{{todo.id}}/" action="post">-->
                <!--              <button type="submit" class="btn btn-sm btn-danger">Delete</button>-->
                <!--            </form>-->
                <!--          </div>-->
                <a class="btn btn-primary" href="{% url 'todo_app:edit' todo.id%}">Edit </a>
                <a href="{% url 'todo_app:delete' todo.id %}"
                   class="confirm-delete" title="Delete" data-toggle="modal"
                   data-target="#confirmDeleteModal"
                   id="deleteButton{{todo.id}}"><button class="btn btn-danger">Delete</button></a>


            </div>
            {%endfor%}
    </ul>
</div>
<div>
    {%block child%}
    {%endblock child%}
</div>
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" caller-id=""
     role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body confirm-delete">
          <h5 class="text-center"> Are you sure you want to delete?</h5>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmDeleteButtonModal">Delete</button>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).on('click', '.confirm-delete', function () {
  $("#confirmDeleteModal").attr("caller-id", $(this).attr("id"));
});

$(document).on('click', '#confirmDeleteButtonModal', function () {
  var caller = $("#confirmDeleteButtonModal").closest(".modal").attr("caller-id");
  window.location = $("#".concat(caller)).attr("href");
});
</script>

{%endif%}
{%endblock parent%}

todo_app/templates/todo_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>ToDo List</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">TODO LIST</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'todo_app:add' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo_app:about' %}">About</a>
                </li>
            </ul>

        </div>
        {% block navbar%}

        {%endblock navbar%}
    </div>
</nav>
<div class="container">

    {% block parent %}

    {% endblock parent %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

todo_app/templates/todo_app/delete.html
{% extends 'todo_app/base.html' %}
{%block parent%}
<div>
    <p>Are you sure you want to delete "{{todo}}"?</p>
<div>
    <a href="{% url 'todo_app:add' %}">
    <button type="submit">
        Close
    </button>
</a>

<form method="POST" action="">
    {% csrf_token %}
    <!--  <input class="btn btn-primary" type="submit" name="Confirm" />-->
    <button type="submit" >Confirm</button>
</form>
</div>
</div>



{%endblock parent%}
<h1> delete item</h1>

todo_app/templates/todo_app/edit.html
{% extends 'todo_app/add.html' %}
{% load crispy_forms_tags %}
{% block child %}
<form method="post" action="{% url 'todo_app:add' %}"> {%csrf_token%}

  {{form|crispy}}
  <input type="submit" value="save"/>
</form>
{% endblock child %}

todo_app/templates/todo_app/login.html
{%extends 'todo_app/add.html'%}
{% load crispy_forms_tags%}
{% block parent %}
<div class="container">
    <div class="row d-flex align-items-center " style="height: 100vh;">
        <div class="col-md-5 mx-auto">
            <div class="todo_container">
                <div class="card top_box rounded-cicle">
                    <div class="top_box p-4 ">
                        <h1 class="display-4 text-center">Login</h1>
                    </div>
                    <div class="card-body">

                         <form action="" method="POST">
                                {% csrf_token %}
                                {{form | crispy}}
                                <div class="d-grid gap-2 mt-3">
                                    <button type="submit" class="btn btn-primary mt-1" type="button">Login</button>
                                </div>
                            </form>
                            <h6 class="mt-2">Create an account: <a href="{% url 'todo_app:signup_user' %}">Sign up</a></h6>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock parent %}

todo_app/templates/todo_app/profile.html
{%extends 'todo_app/add.html'%}
{% load crispy_forms_tags%}
{% block parent %}
<div class="container">
    <div class="row d-flex align-items-center " style="height: 100vh;">
        <div class="col-md-5 mx-auto">
            <div class="todo_container">
                <div class="card top_box rounded-cicle">
                    <div class="top_box p-4 ">
                        <h1 class="display-4 text-center">Login</h1>
                    </div>
                    <div class="card-body">
                          <form action="{%url 'todo_app:profile' %}" method="POST" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {{p_form | crispy}}
                        {{u_form | crispy}}
                        <div class="d-grid gap-2 mt-2">
                            <button type="submit" class="btn btn-primary mt-1" type="button">Update</button>
                          </div>
                    </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock parent %}

todo_app/templates/todo_app/signup.html
{%extends 'todo_app/add.html'%}
{% load crispy_forms_tags%}
{% block parent %}

<div class="container">
    <div class="row d-flex align-items-center " style="height: 100vh;">
        <div class="col-md-5 mx-auto">
            <div class="todo_container">
                <div class="card top_box rounded-cicle">
                    <div class="top_box p-4 ">
                        <h1 class="display-4 text-center">Sign up</h1>
                    </div>
                    <div class="card-body">

                        <form action="" method="POST">
                            {% csrf_token %}
                            {{form | crispy}}
                            <div class="d-grid gap-2 mt-3">
                                <button type="submit" class="btn btn-primary mt-1" type="button">Sign up</button>
                            </div>
                        </form>
                        <br>
                        <h6> Already Have an account: <a href="{% url 'todo_app:login_user' %}">Login</a></h6>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock parent %}